# Generated by Django 5.2.11 on 2026-02-14 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("fetch", "Data Fetch"),
                            ("analysis", "Analysis Run"),
                            ("alert", "Alert Generated"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("success", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("text", models.TextField()),
                ("url", models.URLField(blank=True, max_length=1000, null=True)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                ("related_urls", models.JSONField(blank=True, default=list)),
                ("images", models.JSONField(blank=True, default=list)),
                ("is_analyzed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("news", "News Outlet"),
                            ("social", "Social Media"),
                            ("fact_check", "Fact Check API"),
                            ("web", "Web Source"),
                        ],
                        max_length=20,
                    ),
                ),
                ("credibility_score", models.FloatField(default=5.0)),
                ("is_active", models.BooleanField(default=True)),
                ("last_checked", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MisinformationAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("misinformation_likelihood", models.FloatField(default=0.0)),
                ("credibility_score", models.FloatField(default=0.0)),
                ("bias_score", models.FloatField(default=0.0)),
                ("amplification_risk", models.FloatField(default=0.0)),
                ("estimated_reach", models.IntegerField(default=0)),
                ("velocity_score", models.FloatField(default=0.0)),
                ("societal_impact_score", models.FloatField(default=0.0)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical Risk"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("affected_topics", models.JSONField(blank=True, default=list)),
                ("sentiment_score", models.FloatField(default=0.0)),
                ("emotional_triggers", models.JSONField(blank=True, default=list)),
                ("explanation", models.TextField(blank=True)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("key_indicators", models.JSONField(blank=True, default=list)),
                ("fact_check_results", models.JSONField(blank=True, default=list)),
                ("verified_claims", models.JSONField(blank=True, default=dict)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="core.content",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Misinformation Analyses",
                "ordering": ["-analyzed_at"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                            ("emergency", "Emergency"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("impact_areas", models.JSONField(blank=True, default=list)),
                ("recommended_actions", models.JSONField(blank=True, default=list)),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="core.misinformationanalysis",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="content",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="core.source",
            ),
        ),
        migrations.CreateModel(
            name="TrendAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("topic", models.CharField(max_length=255)),
                ("total_content_analyzed", models.IntegerField(default=0)),
                ("misinformation_count", models.IntegerField(default=0)),
                ("average_risk_score", models.FloatField(default=0.0)),
                ("high_risk_count", models.IntegerField(default=0)),
                ("trending_keywords", models.JSONField(blank=True, default=list)),
                ("source_distribution", models.JSONField(blank=True, default=dict)),
                ("sentiment_distribution", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("date", "topic")},
            },
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["-created_at"], name="core_conten_created_e1bc39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["is_analyzed"], name="core_conten_is_anal_791a05_idx"
            ),
        ),
    ]
