# Generated by Django 5.2.11 on 2026-02-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("article", "News Article"),
                    ("claim", "Claim / Statement"),
                    ("social", "Social Media Post"),
                    ("other", "Other"),
                ],
                default="article",
                max_length=20,
            ),
        ),
    ]
