# Generated by Django 5.2.11 on 2026-02-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_content_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='content',
            name='extraction_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='content',
            name='extraction_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='content',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('article', 'News Article'), ('claim', 'Claim / Statement'), ('social', 'Social Media Post'), ('image', 'Image / Screenshot'), ('audio', 'Audio Clip'), ('other', 'Other')], default='article', max_length=20),
        ),
    ]
